const types = {
    CLEAR_CURRENT: 'CHATS_CLEAR_CURRENT',
    GET_REQUEST: 'CHATS_GET_REQUEST',
    GET_SUCCESS: 'CHATS_GET_SUCCESS',
    GET_FAILURE: 'CHATS_GET_FAILURE',
  
    POST_REQUEST: 'CHATS_POST_REQUEST',
    POST_SUCCESS: 'CHATS_POST_SUCCESS',
    POST_FAILURE: 'CHATS_POST_FAILURE',
  
    GETALL_REQUEST: 'CHATS_GETALL_REQUEST',
    GETALL_SUCCESS: 'CHATS_GETALL_SUCCESS',
    GETALL_FAILURE: 'CHATS_GETALL_FAILURE',
    CLEAR_ALL: "CHATS_CLEAR_ALL",
  
    DELETE_REQUEST: 'CHATS_DELETE_REQUEST',
    DELETE_SUCCESS: 'CHATS_DELETE_SUCCESS',
    DELETE_FAILURE: 'CHATS_DELETE_FAILURE',    
  
    UPDATE_REQUEST: 'CHATS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CHATS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CHATS_UPDATE_FAILURE',
    
   VISTO_REQUEST: "CHATS_VISTO_REQUEST"

  
  };
  
  export default types;