const types = {
    CLEAR_CURRENT: 'USERS_CLEAR_CURRENT',
    GET_REQUEST: 'USERS_GET_REQUEST',
    GET_SUCCESS: 'USERS_GET_SUCCESS',
    GET_FAILURE: 'USERS_GET_FAILURE',
  
    POST_REQUEST: 'USERS_POST_REQUEST',
    POST_SUCCESS: 'USERS_POST_SUCCESS',
    POST_FAILURE: 'USERS_POST_FAILURE',
  
    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',
    CLEAR_ALL: "USERS_CLEAR_ALL",
  
    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',    
  
    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',
    
    UNFOLLOW_REQUEST: 'USERS_UNFOLLOW_REQUEST',
    UNFOLLOW_SUCCCES: 'USERS_UNFOLLOW_SUCCES',
    UNFOLLOW_FAILURE: 'USERS_UNFOLLOW_FAILURE',

    FOLLOW_REQUEST: 'USERS_FOLLOW_REQUEST',
    FOLLOW_SUCCCES: 'USERS_FOLLOW_SUCCES',
    FOLLOW_FAILURE: 'USERS_FOLLOW_FAILURE',

  
  };
  
  export default types;