const types = {
  CLEAR_CURRENT: 'AUTH_CLEAR_CURRENT',
  GET_REQUEST: 'AUTH_GET_REQUEST',
  GET_SUCCESS: 'AUTH_GET_SUCCESS',
  GET_FAILURE: 'AUTH_GET_FAILURE',

  POST_REQUEST: 'AUTH_POST_REQUEST',
  POST_SUCCESS: 'AUTH_POST_SUCCESS',
  POST_FAILURE: 'AUTH_POST_FAILURE',

  GETALL_REQUEST: 'AUTH_GETALL_REQUEST',
  GETALL_SUCCESS: 'AUTH_GETALL_SUCCESS',
  GETALL_FAILURE: 'AUTH_GETALL_FAILURE',

  DELETE_REQUEST: 'AUTH_DELETE_REQUEST',
  DELETE_SUCCESS: 'AUTH_DELETE_SUCCESS',
  DELETE_FAILURE: 'AUTH_DELETE_FAILURE',    

  UPDATE_REQUEST: 'AUTH_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'AUTH_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'AUTH_UPDATE_FAILURE',
  
  FOLLOW_REQUEST: 'AUTH_FOLLOW_REQUEST',
  UNFOLLOW_REQUEST: 'AUTH_UNFOLLOW_REQUEST',

};

export default types;